<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TccZendLoggerPsr\Module'                => __DIR__ . '/Module.php',
    'TccZendLoggerPsr\Factory\LoggerFactory' => __DIR__ . '/src/TccZendLoggerPsr/Factory/LoggerFactory.php',
    'TccZendLoggerPsr\Log\Logger'            => __DIR__ . '/src/TccZendLoggerPsr/Log/Logger.php',
);
